### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [AndrewMLo/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code. There are a few shared properties that you can simplify by applying to multiple selectors at once, rather than individually. There are several properties which are shared among multiple selectors, which you might simplify like so,

```css
h1, h2, .bluebold {
  font-family: Helvetica;
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}
```
